Search
ViktorKatz/wdcookbook pull request #39
Opened 2021-06-27 16:30 UTC by gavantee

kida

2021-06-27 16:30 UTC, gavantee commented
mozda mu treba neka stilizacija

2021-06-28 07:51 UTC, ViktorKatz requested changes
Omg, ovo je fenomenalno! Je l može i `nema komentara izlogovan` i za ocene?

2021-06-28 09:52 UTC, gavantee commented
htedoh reći ocene

2021-06-28 13:15 UTC, ViktorKatz approved these changes

2021-06-28 13:15 UTC, ViktorKatz commented
Ovo je cool, al me mrzi da testiram... Verujem ti da sve radi!

2021-06-28 13:44 UTC, merged